In [1]:
[3, 5, 9]

3-element Array{Int64,1}:
 3
 5
 9

In [2]:
[3, 5, 9] + [1, 2, 3]

3-element Array{Int64,1}:
  4
  7
 12

In [5]:
arr = ["Hello", 2, 45.7, true]

4-element Array{Any,1}:
     "Hello"
    2
   45.7
 true

In [10]:
println(arr[3])
println(arr[2:4])

45.7
Any[2, 45.7, true]


In [6]:
length(ans)

4

In [8]:
println(minimum([3, 5, 9]))
println(maximum([3, 5, 9]))

3
9


In [13]:
println(zeros(4))
println(ones(3))

[0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 1.0]


In [14]:
push!(arr, "34")   # adiciona elementos no final da matriz

5-element Array{Any,1}:
     "Hello"
    2
   45.7
 true
     "34"

In [16]:
sort([3, 5, -1])

3-element Array{Int64,1}:
 -1
  3
  5

In [20]:
println(range(1, stop=100))
println(range(-10, step=5, length=10))
println(range(-10, length=10))

1:100
-10:5:35
-10:-1


In [27]:
arr1 = arr   # ao usar esse comando tudo que for alterado em arr1 também será feito em arr
arr1[1]= "Bye"  # substitui o primeiro elemento do array

"Bye"

In [26]:
println(arr1, "\n", arr)

Any["Bye", 2, 45.7, true, "34"]
Any["Bye", 2, 45.7, true, "34"]


In [28]:
arr2 = copy(arr)

5-element Array{Any,1}:
     "Bye"
    2
   45.7
 true
     "34"

In [29]:
println(arr, "\n", arr2)

Any["Bye", 2, 45.7, true, "34"]
Any["Bye", 2, 45.7, true, "34"]


In [30]:
arr2[1]= "Julia"

"Julia"

In [31]:
println(arr, "\n", arr2)

Any["Bye", 2, 45.7, true, "34"]
Any["Julia", 2, 45.7, true, "34"]
