# Vector & Matrix Processing

## Random package

In [3]:
Pkg.add("Random")

   Updating registry at `C:\Users\andre\.juliapro\JuliaPro_v1.4.0-1\registries\JuliaPro`
  Resolving package versions...
   Updating `C:\Users\andre\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Project.toml`
  [9a3f8284] + Random 
   Updating `C:\Users\andre\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Manifest.toml`
 [no changes]


In [4]:
using Random

In [5]:
rand(3,4)

3×4 Array{Float64,2}:
 0.772797  0.0673155  0.924096  0.0666749
 0.477706  0.493111   0.372874  0.88978
 0.346534  0.997876   0.411852  0.947858

In [6]:
randn(10,2)

10×2 Array{Float64,2}:
 -0.385153    0.212969
 -0.253855   -0.165284
  0.903723   -0.310094
  1.15008     0.114028
 -0.0878144   0.62419
 -0.270022   -1.07387
 -0.915938    1.1037
 -0.596702    0.28926
  0.0894898   0.309874
  0.0957901  -2.05922

In [7]:
randstring()

"b1T30Eb4"

In [8]:
randstring('A':'C', 20)

"CBCACBCACBABAACABAAC"

In [11]:
v1 = Vector(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [15]:
reshape(v1, (2,5))

2×5 Array{Int64,2}:
 1  3  5  7   9
 2  4  6  8  10

## Algebra Operations

In [16]:
ones(3,5)

3×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [17]:
zeros(2,5)

2×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [19]:
zeros(2,5, 6)

2×5×6 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 4] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 5] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

[:, :, 6] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [20]:
Pkg.add("LinearAlgebra")

  Resolving package versions...
   Updating `C:\Users\andre\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Project.toml`
  [37e2e46d] + LinearAlgebra 
   Updating `C:\Users\andre\.juliapro\JuliaPro_v1.4.0-1\environments\v1.4\Manifest.toml`
 [no changes]


In [21]:
using LinearAlgebra

In [23]:
I(10) # Matriz identidade

10×10 Diagonal{Bool,Array{Bool,1}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1

In [25]:
M = [2 4 5; 1 2 3; 6 7 0]

3×3 Array{Int64,2}:
 2  4  5
 1  2  3
 6  7  0

In [26]:
typeof(M)

Array{Int64,2}

In [27]:
size(M)

(3, 3)

In [31]:
println(M[1,:])
println(M[:,2])

[2, 4, 5]
[4, 2, 7]


In [32]:
N = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [33]:
[M; N]      # concatena pela vertical

6×3 Array{Int64,2}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [34]:
hcat(M, N)    # concatenação pela horizontal

3×6 Array{Int64,2}:
 2  4  5  1  2  3
 1  2  3  4  5  6
 6  7  0  7  8  9

In [35]:
vcat(M,N)    # concatenação pela vertical

6×3 Array{Int64,2}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [37]:
transpose(M) # Matrix transposta

3×3 Transpose{Int64,Array{Int64,2}}:
 2  1  6
 4  2  7
 5  3  0

In [38]:
tr(M)

4

In [40]:
det(M)  # determinante

5.000000000000001

In [41]:
inv(M)

3×3 Array{Float64,2}:
 -4.2   7.0   0.4
  3.6  -6.0  -0.2
 -1.0   2.0   0.0

In [45]:
UpperTriangular(M)

3×3 UpperTriangular{Int64,Array{Int64,2}}:
 2  4  5
 ⋅  2  3
 ⋅  ⋅  0

In [46]:
LowerTriangular(M)

3×3 LowerTriangular{Int64,Array{Int64,2}}:
 2  ⋅  ⋅
 1  2  ⋅
 6  7  0

In [48]:
eigvecs(M)  # autovetores
eigvals(M)  # autovalores

3-element Array{Float64,1}:
 -5.352954259951673
 -0.09882411688237432
  9.451778376834048